export const countryOptions = [
  { value: "ALL", label: "Everywhere" },
  { value: "USA", label: "United States" },
  { value: "ARG", label: "Argentina" },
  { value: "AUS", label: "Australia" },
  { value: "BGR", label: "Bulgaria" },
  { value: "CAN", label: "Canada" },
  { value: "CHL", label: "Chile" },
  { value: "COL", label: "Colombia" },
  { value: "HRV", label: "Croatia" },
  { value: "CZE", label: "Czech Republic" },
  { value: "FIN", label: "Finland" },
  { value: "GRC", label: "Greece" },
  { value: "HUN", label: "Hungary" },
  { value: "ISL", label: "Iceland" },
  { value: "IND", label: "India" },
  { value: "IRL", label: "Ireland" },
  { value: "JPN", label: "Japan" },
  { value: "MYS", label: "Malaysia" },
  { value: "MEX", label: "Mexico" },
  { value: "NZL", label: "New Zealand" },
  { value: "PHL", label: "Philippines" },
  { value: "POL", label: "Poland" },
  { value: "PRT", label: "Portugal" },
  { value: "PRI", label: "Puerto Rico" },
  { value: "ROU", label: "Romania" },
  { value: "SRB", label: "Serbia" },
  { value: "SGP", label: "Singapore" },
  { value: "SWE", label: "Sweden" },
  { value: "TWN", label: "Taiwan" },
  { value: "THA", label: "Thailand" },
  { value: "TUR", label: "Turkey" },
  { value: "GBR", label: "United Kingdom" },
];

export const sortOptions = [
  { value: "hot", label: "Hot", icon: "fire" },
  { value: "new", label: "New", icon: "dice-d6" },
  { value: "controversial", label: "Controversial", icon: "bolt" },
  { value: "top", label: "Top", icon: "chart-line" },
  { value: "rising", label: "Rising", icon: "chart-bar" },
];

export const dateOptions = [
  { value: "now", label: "Now" },
  { value: "new", label: "Today" },
  { value: "thisweek", label: "This Week" },
  { value: "thismonth", label: "This Month" },
  { value: "thisyear", label: "This Year" },
  { value: "alltime", label: "All Time" },
];
